# Generated by Django 4.1 on 2022-09-24 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PizzaDelivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount_Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=6)),
                ('is_applied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Discount_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('discount', models.FloatField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('order_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=10)),
                ('total_amount', models.FloatField(max_length=6)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField(max_length=5)),
                ('total_price', models.FloatField(max_length=5)),
                ('is_paid', models.BooleanField(default=False)),
                ('order_id', models.CharField(default='', max_length=7, null=True)),
                ('order_status', models.CharField(default='not_ordered', max_length=20, null=True)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PizzaDelivery.pizza')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
